local M = require('xe.node_def._checker')
local CalcParamNum = M.CalcParamNum
local CheckName = M.CheckName
local CheckVName = M.CheckVName
local CheckExpr = M.CheckExpr
local CheckPos = M.CheckPos
local CheckExprOmit = M.CheckExprOmit
local CheckCode = M.CheckCode
local CheckParam = M.CheckParam
local CheckNonBlank = M.CheckNonBlank
local CheckClassName = M.CheckClassName
local IsBlank = M.IsBlank
local CheckResFileInPack = M.CheckResFileInPack
local CheckAnonymous = M.CheckAnonymous
local MakeFullPath = M.MakeFullPath

local fmt = [[-- Generated by LuaSTG-x editor
-- Mod name: %s
_author = %q
_mod_version = %d
_allow_practice = %s
_allow_sc_practice = %s

]]
local setting = {
    { 'Output name', 'any', CheckName },
    { 'Author', 'any', CheckName },
    { 'Allow practice', 'bool', CheckExpr },
    { 'Allow sc practice', 'bool', CheckExpr },
    disptype     = {
        en = 'project settings',
        zh = '设置',
    },
    totext       = function(nodedata)
        return 'project settings'
    end,
    allowparent  = {},
    allowchild   = {},
    forbiddelete = true,
    tohead       = function(nodedata)
        return string.format(
                fmt,
                nodedata.attr[1], nodedata.attr[2], _luastg_version, nodedata.attr[3], nodedata.attr[4])
    end,
}

require('xe.node_def._def').DefineNode('setting', setting)
