--

local M = {
    -- パーツID
    HitAreaPrefix   = "HitArea",
    HitAreaHead     = "Head",
    HitAreaBody     = "Body",
    PartsIdCore     = "Parts01Core",
    PartsArmPrefix  = "Parts01Arm_",
    PartsArmLPrefix = "Parts01ArmL_",
    PartsArmRPrefix = "Parts01ArmR_",

    -- パラメータID
    AngleX          = "ParamAngleX",
    AngleY          = "ParamAngleY",
    AngleZ          = "ParamAngleZ",
    EyeLOpen        = "ParamEyeLOpen",
    EyeLSmile       = "ParamEyeLSmile",
    EyeROpen        = "ParamEyeROpen",
    EyeRSmile       = "ParamEyeRSmile",
    EyeBallX        = "ParamEyeBallX",
    EyeBallY        = "ParamEyeBallY",
    EyeBallForm     = "ParamEyeBallForm",
    BrowLY          = "ParamBrowLY",
    BrowRY          = "ParamBrowRY",
    BrowLX          = "ParamBrowLX",
    BrowRX          = "ParamBrowRX",
    BrowLAngle      = "ParamBrowLAngle",
    BrowRAngle      = "ParamBrowRAngle",
    BrowLForm       = "ParamBrowLForm",
    BrowRForm       = "ParamBrowRForm",
    MouthForm       = "ParamMouthForm",
    MouthOpenY      = "ParamMouthOpenY",
    Cheek           = "ParamCheek",
    BodyAngleX      = "ParamBodyAngleX",
    BodyAngleY      = "ParamBodyAngleY",
    BodyAngleZ      = "ParamBodyAngleZ",
    Breath          = "ParamBreath",
    ArmLA           = "ParamArmLA",
    ArmRA           = "ParamArmRA",
    ArmLB           = "ParamArmLB",
    ArmRB           = "ParamArmRB",
    HandL           = "ParamHandL",
    HandR           = "ParamHandR",
    HairFront       = "ParamHairFront",
    HairSide        = "ParamHairSide",
    HairBack        = "ParamHairBack",
    HairFluffy      = "ParamHairFluffy",
    ShoulderY       = "ParamShoulderY",
    BustX           = "ParamBustX",
    BustY           = "ParamBustY",
    BaseX           = "ParamBaseX",
    BaseY           = "ParamBaseY",
    NONE            = "NONE:",
}

return M
