local M = {
    {
        label   = 'File',
        name    = "PanelFile",
        content = {
            { name   = "ToolNew",
              bitmap = 'images/toolbar/new.png',
            },
            { name   = "ToolOpen",
              bitmap = 'images/toolbar/open.png',
            },
            { name   = "ToolSave",
              bitmap = 'images/toolbar/save.png',
            },
            { name   = "ToolClose",
              bitmap = 'images/toolbar/delete.png',
            },
            { name   = "ToolMerge",
              bitmap = 'images/toolbar/merge.png',
            },
        },
    },
    {
        label   = 'General',
        name    = "PanelGeneral",
        content = {
            { name   = "Insert_folder",
              bitmap = 'images/folder.png',
            },
            { name   = "Insert_codeblock",
              bitmap = 'images/codeblock.png',
            },
            { name   = "Insert_if",
              bitmap = 'images/if.png',
            },
            { name   = "Insert_variable",
              bitmap = 'images/variable.png',
            },
            { name   = "Insert_repeat",
              bitmap = 'images/repeat.png',
            },
            { name   = "Insert_code",
              bitmap = 'images/code.png',
            },
            { name   = "Insert_comment",
              bitmap = 'images/comment.png',
            },
            { name   = "Insert_patch",
              bitmap = 'images/patch.png',
            },
        },
    },
    {
        label   = 'Stage',
        name    = "PanelStage",
        content = {
            { name   = "Insert_stagegroup",
              bitmap = 'images/stagegroup.png',
            },
            { name   = "Insert_stage",
              bitmap = 'images/stage.png',
            },
            { name   = "Insert_stagegoto",
              bitmap = 'images/stagegoto.png',
            },
            { name   = "Insert_stagefinish",
              bitmap = 'images/stagefinish.png',
            },
            { name   = "Insert_stagefinishgroup",
              bitmap = 'images/stagefinishgroup.png',
            },
            { name   = "Insert_bgstage",
              bitmap = 'images/bgstage.png',
            },
        },
    },
    {
        label   = 'Task',
        name    = "PanelTask",
        content = {
            { name   = "Insert_task",
              bitmap = 'images/task.png',
            },
            { name   = "Insert_tasker",
              bitmap = 'images/tasker.png',
            },
            { name   = "Insert_taskwait",
              bitmap = 'images/taskwait.png',
            },
            { name   = "Insert_taskrepeat",
              bitmap = 'images/taskrepeat.png',
            },
            { name   = "Insert_taskbreak",
              bitmap = 'images/taskbreak.png',
            },
            { name   = "Insert_taskmoveto",
              bitmap = 'images/taskmoveto.png',
            },
            { name   = "Insert_taskBeziermoveto",
              bitmap = 'images/taskBeziermoveto.png',
            },
            { name   = "Insert_taskreturn",
              bitmap = 'images/taskreturn.png',
            },
            { name   = "Insert_taskclear",
              bitmap = 'images/taskclear.png',
            },
        },
    },
    {
        label   = 'Enemy',
        name    = "PanelEnemy",
        content = {
            { name   = "Insert_enemydefine",
              bitmap = 'images/enemydefine.png',
            },
            { name   = "Insert_enemycreate",
              bitmap = 'images/enemycreate.png',
            },
            { name   = "Insert_enemysimple",
              bitmap = 'images/enemysimple.png',
            },
        },
    },
    {
        label   = 'Boss',
        name    = "PanelBoss",
        content = {
            { name   = "Insert_bossdefine",
              bitmap = 'images/bossdefine.png',
            },
            { name   = "Insert_bossspellcard",
              bitmap = 'images/bossspellcard.png',
            },
            { name   = "Insert_bossmoveto",
              bitmap = 'images/bossmoveto.png',
            },
            { name   = "Insert_dialog",
              bitmap = 'images/dialog.png',
            },
            { name   = "Insert_sentence",
              bitmap = 'images/sentence.png',
            },
            { name   = "Insert_taskbosswander",
              bitmap = 'images/taskbosswander.png',
            },
            { name   = "Insert_bosscast",
              bitmap = 'images/bosscast.png',
            },
            { name   = "Insert_bossshowaura",
              bitmap = 'images/bossshowaura.png',
            },
            { name   = "Insert_pactrometer",
              bitmap = 'images/pactrometer.png',
            },
            { name   = "Insert_explode",
              bitmap = 'images/explode.png',
            },
            { name   = "Insert_bosscreate",
              bitmap = 'images/bosscreate.png',
            },
            { name   = "Insert_bgdefine",
              bitmap = 'images/bgdefine.png',
            },
            { name   = "Insert_bglayer",
              bitmap = 'images/bglayer.png',
            },
        },
    },
    {
        label   = 'Bullet',
        name    = "PanelBullet",
        content = {
            { name   = "Insert_bulletdefine",
              bitmap = 'images/bulletdefine.png',
            },
            { name   = "Insert_bulletcreate",
              bitmap = 'images/bulletcreate.png',
            },
            { name   = "Insert_bulletchangestyle",
              bitmap = 'images/bulletchangestyle.png',
            },
            { name   = "Insert_bulletcreatestraight",
              bitmap = 'images/bulletcreatestraight.png',
            },
            { name   = "Insert_bulletcreatestraightex",
              bitmap = 'images/bulletcreatestraightex.png',
            },
            { name   = "Insert_bulletclear",
              bitmap = 'images/bulletclear.png',
            },
            { name   = "Insert_bulletcleanrange",
              bitmap = 'images/bulletcleanrange.png',
            },
        },
    },
    {
        label   = 'Tools',
        name    = "PanelTools",
        content = {
            { name   = "Insert_rebounderdefine",
              bitmap = 'images/rebounderdefine.png',
            },
            { name   = "Insert_reboundercreate",
              bitmap = 'images/reboundercreate.png',
            },
            { name   = "Insert_simplerebounder",
              bitmap = 'images/simplerebounder.png',
            },
        },
    },
    --[[{
        label   = 'BulletEx',
        name    = "PanelBulletEx",
        content = {
            { name   = "Insert_iteration",
              bitmap = 'images/iteration.png',
            },
            { name   = "Insert_shooter",
              bitmap = 'images/shooter.png',
            },
            { name   = "Insert_lasershooter",
              bitmap = 'images/lasershooter.png',
            },
            { name   = "Insert_bentlasershooter",
              bitmap = 'images/bentlasershooter.png',
            },
            { name   = "Insert__node_atp",
              bitmap = 'images/_node_atp.png',
            },
            { name   = "Insert__node_g",
              bitmap = 'images/_node_g.png',
            },
            { name   = "Insert__node_accel",
              bitmap = 'images/_node_accel.png',
            },
            { name   = "Insert__node_stay",
              bitmap = 'images/_node_stay.png',
            },
            { name   = "Insert__node_vf",
              bitmap = 'images/_node_vf.png',
            },
            { name   = "Insert__node_pro",
              bitmap = 'images/_node_pro.png',
            },
            { name   = "Insert__node_dir",
              bitmap = 'images/_node_dir.png',
            },
            { name   = "Insert__node_aa",
              bitmap = 'images/_node_aa.png',
            },
            { name   = "Insert__node_moveto",
              bitmap = 'images/_node_moveto.png',
            },
            { name   = "Insert__node_rot",
              bitmap = 'images/_node_rot.png',
            },
            { name   = "Insert__node_pe",
              bitmap = 'images/_node_pe.png',
            },
            { name   = "Insert__node_toc",
              bitmap = 'images/_node_toc.png',
            },
            { name   = "Insert__node_tof",
              bitmap = 'images/_node_tof.png',
            },
        },
    },]]
    {
        label   = 'Laser',
        name    = "PanelLaser",
        content = {
            { name   = "Insert_laserdefine",
              bitmap = 'images/laserdefine.png',
            },
            { name   = "Insert_lasercreate",
              bitmap = 'images/lasercreate.png',
            },
            { name   = "Insert_laserturnhalfon",
              bitmap = 'images/laserturnhalfon.png',
            },
            { name   = "Insert_laserturnon",
              bitmap = 'images/laserturnon.png',
            },
            { name   = "Insert_laserturnoff",
              bitmap = 'images/laserturnoff.png',
            },
            { name   = "Insert_lasergrow",
              bitmap = 'images/lasergrow.png',
            },
            { name   = "Insert_laserchange",
              bitmap = 'images/laserchange.png',
            },
            { name   = "Insert_laserbentdefine",
              bitmap = 'images/laserbentdefine.png',
            },
            { name   = "Insert_laserbentcreate",
              bitmap = 'images/laserbentcreate.png',
            },
        },
    },
    {
        label   = 'Object',
        name    = "PanelObject",
        content = {
            { name   = "Insert_objectdefine",
              bitmap = 'images/objectdefine.png',
            },
            { name   = "Insert_objectcreate",
              bitmap = 'images/objectcreate.png',
            },
            { name   = "Insert_setcolor",
              bitmap = 'images/setcolor.png',
            },
            { name   = "Insert_objectsetimg",
              bitmap = 'images/objectsetimg.png',
            },
        },
    },
    {
        label   = 'Unit',
        name    = "PanelUnit",
        content = {
            { name   = "Insert_callbackfunc",
              bitmap = 'images/callbackfunc.png',
            },
            { name   = "Insert_defaultaction",
              bitmap = 'images/defaultaction.png',
            },
            { name   = "Insert_setv",
              bitmap = 'images/setv.png',
            },
            { name   = "Insert_setaccel",
              bitmap = 'images/setaccel.png',
            },
            { name   = "Insert_setgravity",
              bitmap = 'images/setgravity.png',
            },
            { name   = "Insert_setfv",
              bitmap = 'images/setfv.png',
            },
            { name   = "Insert_unitkill",
              bitmap = 'images/unitkill.png',
            },
            { name   = "Insert_unitdel",
              bitmap = 'images/unitdel.png',
            },
            { name   = "Insert_unitforeach",
              bitmap = 'images/unitforeach.png',
            },
            { name   = "Insert_connect",
              bitmap = 'images/connect.png',
            },
            { name   = "Insert_setrelpos",
              bitmap = 'images/setrelpos.png',
            },
        },
    },
    {
        label   = 'Audio',
        name    = "PanelAudio",
        content = {
            { name   = "Insert_loadsound",
              bitmap = 'images/loadsound.png',
            },
            { name   = "Insert_playsound",
              bitmap = 'images/playsound.png',
            },
            { name   = "Insert_loadbgm",
              bitmap = 'images/loadbgm.png',
            },
            { name   = "Insert_playbgm",
              bitmap = 'images/playbgm.png',
            },
            { name   = "Insert_pausebgm",
              bitmap = 'images/pausebgm.png',
            },
            { name   = "Insert_resumebgm",
              bitmap = 'images/resumebgm.png',
            },
            { name   = "Insert_stopbgm",
              bitmap = 'images/stopbgm.png',
            },
        },
    },
    {
        label   = 'Graphics',
        name    = "PanelGraphics",
        content = {
            { name   = "Insert_loadimage",
              bitmap = 'images/loadimage.png',
            },
            { name   = "Insert_loadani",
              bitmap = 'images/loadani.png',
            },
            { name   = "Insert_loadparticle",
              bitmap = 'images/loadparticle.png',
            },
            { name   = "Insert_loadimagegroup",
              bitmap = 'images/loadimagegroup.png',
            },
            { name   = "Insert_loadtexture",
              bitmap = 'images/loadtexture.png',
            },
            { name   = "Insert_renderimage",
              bitmap = 'images/renderimage.png',
            },
        },
    },
    {
        label   = 'Effects',
        name    = "PanelEffects",
        content = {
            { name   = "Insert_shakescreen",
              bitmap = 'images/shakescreen.png',
            },
            { name   = "Insert_dropitem",
              bitmap = 'images/dropitem.png',
            },
            { name   = "Insert_loadFX",
              bitmap = 'images/loadFX.png',
            },
            { name   = "Insert_smear",
              bitmap = 'images/smear.png',
            },
        },
    },
}

return M
