---
--- color_def.lua
---
--- Copyright (C) 2018-2020 Xrysnow. All rights reserved.
---


color                      = color or {}

---Predefined colors. From C#.

local _

color.AliceBlue            = Color(0xFFF0F8FF) _=[[._{color:#F0F8FF;}]]---@language CSS
color.AntiqueWhite         = Color(0xFFFAEBD7) _=[[._{color:#FAEBD7;}]]---@language CSS
color.Aqua                 = Color(0xFF00FFFF) _=[[._{color:#00FFFF;}]]---@language CSS
color.Aquamarine           = Color(0xFF7FFFD4) _=[[._{color:#7FFFD4;}]]---@language CSS
color.Azure                = Color(0xFFF0FFFF) _=[[._{color:#F0FFFF;}]]---@language CSS
color.Beige                = Color(0xFFF5F5DC) _=[[._{color:#F5F5DC;}]]---@language CSS
color.Bisque               = Color(0xFFFFE4C4) _=[[._{color:#FFE4C4;}]]---@language CSS
color.Black                = Color(0xFF000000) _=[[._{color:#000000;}]]---@language CSS
color.BlanchedAlmond       = Color(0xFFFFFFCD) _=[[._{color:#FFFFCD;}]]---@language CSS
color.Blue                 = Color(0xFF0000FF) _=[[._{color:#0000FF;}]]---@language CSS
color.BlueViolet           = Color(0xFF8A2BE2) _=[[._{color:#8A2BE2;}]]---@language CSS
color.Brown                = Color(0xFFA52A2A) _=[[._{color:#A52A2A;}]]---@language CSS
color.BurlyWood            = Color(0xFFDEB887) _=[[._{color:#DEB887;}]]---@language CSS
color.CadetBlue            = Color(0xFF5F9EA0) _=[[._{color:#5F9EA0;}]]---@language CSS
color.Chartreuse           = Color(0xFF7FFF00) _=[[._{color:#7FFF00;}]]---@language CSS
color.Chocolate            = Color(0xFFD2691E) _=[[._{color:#D2691E;}]]---@language CSS
color.Coral                = Color(0xFFFF7F50) _=[[._{color:#FF7F50;}]]---@language CSS
color.CornflowerBlue       = Color(0xFF6495ED) _=[[._{color:#6495ED;}]]---@language CSS
color.Cornsilk             = Color(0xFFFFF8DC) _=[[._{color:#FFF8DC;}]]---@language CSS
color.Crimson              = Color(0xFFDC143C) _=[[._{color:#DC143C;}]]---@language CSS
color.Cyan                 = Color(0xFF00FFFF) _=[[._{color:#00FFFF;}]]---@language CSS
color.DarkBlue             = Color(0xFF00008B) _=[[._{color:#00008B;}]]---@language CSS
color.DarkCyan             = Color(0xFF008B8B) _=[[._{color:#008B8B;}]]---@language CSS
color.DarkGoldenrod        = Color(0xFFB8860B) _=[[._{color:#B8860B;}]]---@language CSS
color.DarkGray             = Color(0xFFA9A9A9) _=[[._{color:#A9A9A9;}]]---@language CSS
color.DarkGreen            = Color(0xFF006400) _=[[._{color:#006400;}]]---@language CSS
color.DarkKhaki            = Color(0xFFBDB76B) _=[[._{color:#BDB76B;}]]---@language CSS
color.DarkMagena           = Color(0xFF8B008B) _=[[._{color:#8B008B;}]]---@language CSS
color.DarkOliveGreen       = Color(0xFF556B2F) _=[[._{color:#556B2F;}]]---@language CSS
color.DarkOrange           = Color(0xFFFF8C00) _=[[._{color:#FF8C00;}]]---@language CSS
color.DarkOrchid           = Color(0xFF9932CC) _=[[._{color:#9932CC;}]]---@language CSS
color.DarkRed              = Color(0xFF8B0000) _=[[._{color:#8B0000;}]]---@language CSS
color.DarkSalmon           = Color(0xFFE9967A) _=[[._{color:#E9967A;}]]---@language CSS
color.DarkSeaGreen         = Color(0xFF8FBC8F) _=[[._{color:#8FBC8F;}]]---@language CSS
color.DarkSlateBlue        = Color(0xFF483D8B) _=[[._{color:#483D8B;}]]---@language CSS
color.DarkSlateGray        = Color(0xFF284F4F) _=[[._{color:#284F4F;}]]---@language CSS
color.DarkTurquoise        = Color(0xFF00CED1) _=[[._{color:#00CED1;}]]---@language CSS
color.DarkViolet           = Color(0xFF9400D3) _=[[._{color:#9400D3;}]]---@language CSS
color.DeepPink             = Color(0xFFFF1493) _=[[._{color:#FF1493;}]]---@language CSS
color.DeepSkyBlue          = Color(0xFF00BFFF) _=[[._{color:#00BFFF;}]]---@language CSS
color.DimGray              = Color(0xFF696969) _=[[._{color:#696969;}]]---@language CSS
color.DodgerBlue           = Color(0xFF1E90FF) _=[[._{color:#1E90FF;}]]---@language CSS
color.Firebrick            = Color(0xFFB22222) _=[[._{color:#B22222;}]]---@language CSS
color.FloralWhite          = Color(0xFFFFFAF0) _=[[._{color:#FFFAF0;}]]---@language CSS
color.ForestGreen          = Color(0xFF228B22) _=[[._{color:#228B22;}]]---@language CSS
color.Fuschia              = Color(0xFFFF00FF) _=[[._{color:#FF00FF;}]]---@language CSS
color.Gainsboro            = Color(0xFFDCDCDC) _=[[._{color:#DCDCDC;}]]---@language CSS
color.GhostWhite           = Color(0xFFF8F8FF) _=[[._{color:#F8F8FF;}]]---@language CSS
color.Gold                 = Color(0xFFFFD700) _=[[._{color:#FFD700;}]]---@language CSS
color.Goldenrod            = Color(0xFFDAA520) _=[[._{color:#DAA520;}]]---@language CSS
color.Gray                 = Color(0xFF808080) _=[[._{color:#808080;}]]---@language CSS
color.Green                = Color(0xFF008000) _=[[._{color:#008000;}]]---@language CSS
color.GreenYellow          = Color(0xFFADFF2F) _=[[._{color:#ADFF2F;}]]---@language CSS
color.Honeydew             = Color(0xFFF0FFF0) _=[[._{color:#F0FFF0;}]]---@language CSS
color.HotPink              = Color(0xFFFF69B4) _=[[._{color:#FF69B4;}]]---@language CSS
color.IndianRed            = Color(0xFFCD5C5C) _=[[._{color:#CD5C5C;}]]---@language CSS
color.Indigo               = Color(0xFF4B0082) _=[[._{color:#4B0082;}]]---@language CSS
color.Ivory                = Color(0xFFFFF0F0) _=[[._{color:#FFF0F0;}]]---@language CSS
color.Khaki                = Color(0xFFF0E68C) _=[[._{color:#F0E68C;}]]---@language CSS
color.Lavender             = Color(0xFFE6E6FA) _=[[._{color:#E6E6FA;}]]---@language CSS
color.LavenderBlush        = Color(0xFFFFF0F5) _=[[._{color:#FFF0F5;}]]---@language CSS
color.LawnGreen            = Color(0xFF7CFC00) _=[[._{color:#7CFC00;}]]---@language CSS
color.LemonChiffon         = Color(0xFFFFFACD) _=[[._{color:#FFFACD;}]]---@language CSS
color.LightBlue            = Color(0xFFADD8E6) _=[[._{color:#ADD8E6;}]]---@language CSS
color.LightCoral           = Color(0xFFF08080) _=[[._{color:#F08080;}]]---@language CSS
color.LightCyan            = Color(0xFFE0FFFF) _=[[._{color:#E0FFFF;}]]---@language CSS
color.LightGoldenrodYellow = Color(0xFFFAFAD2) _=[[._{color:#FAFAD2;}]]---@language CSS
color.LightGreen           = Color(0xFF90EE90) _=[[._{color:#90EE90;}]]---@language CSS
color.LightGray            = Color(0xFFD3D3D3) _=[[._{color:#D3D3D3;}]]---@language CSS
color.LightPink            = Color(0xFFFFB6C1) _=[[._{color:#FFB6C1;}]]---@language CSS
color.LightSalmon          = Color(0xFFFFA07A) _=[[._{color:#FFA07A;}]]---@language CSS
color.LightSeaGreen        = Color(0xFF20B2AA) _=[[._{color:#20B2AA;}]]---@language CSS
color.LightSkyBlue         = Color(0xFF87CEFA) _=[[._{color:#87CEFA;}]]---@language CSS
color.LightSlateGray       = Color(0xFF778899) _=[[._{color:#778899;}]]---@language CSS
color.LightSteelBlue       = Color(0xFFB0C4DE) _=[[._{color:#B0C4DE;}]]---@language CSS
color.LightYellow          = Color(0xFFFFFFE0) _=[[._{color:#FFFFE0;}]]---@language CSS
color.Lime                 = Color(0xFF00FF00) _=[[._{color:#00FF00;}]]---@language CSS
color.LimeGreen            = Color(0xFF32CD32) _=[[._{color:#32CD32;}]]---@language CSS
color.Linen                = Color(0xFFFAF0E6) _=[[._{color:#FAF0E6;}]]---@language CSS
color.Magenta              = Color(0xFFFF00FF) _=[[._{color:#FF00FF;}]]---@language CSS
color.Maroon               = Color(0xFF800000) _=[[._{color:#800000;}]]---@language CSS
color.MediumAquamarine     = Color(0xFF66CDAA) _=[[._{color:#66CDAA;}]]---@language CSS
color.MediumBlue           = Color(0xFF0000CD) _=[[._{color:#0000CD;}]]---@language CSS
color.MediumOrchid         = Color(0xFFBA55D3) _=[[._{color:#BA55D3;}]]---@language CSS
color.MediumPurple         = Color(0xFF9370DB) _=[[._{color:#9370DB;}]]---@language CSS
color.MediumSeaGreen       = Color(0xFF3CB371) _=[[._{color:#3CB371;}]]---@language CSS
color.MediumSlateBlue      = Color(0xFF7B68EE) _=[[._{color:#7B68EE;}]]---@language CSS
color.MediumSpringGreen    = Color(0xFF00FA9A) _=[[._{color:#00FA9A;}]]---@language CSS
color.MediumTurquoise      = Color(0xFF48D1CC) _=[[._{color:#48D1CC;}]]---@language CSS
color.MediumVioletRed      = Color(0xFFC71570) _=[[._{color:#C71570;}]]---@language CSS
color.MidnightBlue         = Color(0xFF191970) _=[[._{color:#191970;}]]---@language CSS
color.MintCream            = Color(0xFFF5FFFA) _=[[._{color:#F5FFFA;}]]---@language CSS
color.MistyRose            = Color(0xFFFFE4E1) _=[[._{color:#FFE4E1;}]]---@language CSS
color.Moccasin             = Color(0xFFFFE4B5) _=[[._{color:#FFE4B5;}]]---@language CSS
color.NavajoWhite          = Color(0xFFFFDEAD) _=[[._{color:#FFDEAD;}]]---@language CSS
color.Navy                 = Color(0xFF000080) _=[[._{color:#000080;}]]---@language CSS
color.OldLace              = Color(0xFFFDF5E6) _=[[._{color:#FDF5E6;}]]---@language CSS
color.Olive                = Color(0xFF808000) _=[[._{color:#808000;}]]---@language CSS
color.OliveDrab            = Color(0xFF6B8E2D) _=[[._{color:#6B8E2D;}]]---@language CSS
color.Orange               = Color(0xFFFFA500) _=[[._{color:#FFA500;}]]---@language CSS
color.OrangeRed            = Color(0xFFFF4500) _=[[._{color:#FF4500;}]]---@language CSS
color.Orchid               = Color(0xFFDA70D6) _=[[._{color:#DA70D6;}]]---@language CSS
color.PaleGoldenrod        = Color(0xFFEEE8AA) _=[[._{color:#EEE8AA;}]]---@language CSS
color.PaleGreen            = Color(0xFF98FB98) _=[[._{color:#98FB98;}]]---@language CSS
color.PaleTurquoise        = Color(0xFFAFEEEE) _=[[._{color:#AFEEEE;}]]---@language CSS
color.PaleVioletRed        = Color(0xFFDB7093) _=[[._{color:#DB7093;}]]---@language CSS
color.PapayaWhip           = Color(0xFFFFEFD5) _=[[._{color:#FFEFD5;}]]---@language CSS
color.PeachPuff            = Color(0xFFFFDA9B) _=[[._{color:#FFDA9B;}]]---@language CSS
color.Peru                 = Color(0xFFCD853F) _=[[._{color:#CD853F;}]]---@language CSS
color.Pink                 = Color(0xFFFFC0CB) _=[[._{color:#FFC0CB;}]]---@language CSS
color.Plum                 = Color(0xFFDDA0DD) _=[[._{color:#DDA0DD;}]]---@language CSS
color.PowderBlue           = Color(0xFFB0E0E6) _=[[._{color:#B0E0E6;}]]---@language CSS
color.Purple               = Color(0xFF800080) _=[[._{color:#800080;}]]---@language CSS
color.Red                  = Color(0xFFFF0000) _=[[._{color:#FF0000;}]]---@language CSS
color.RosyBrown            = Color(0xFFBC8F8F) _=[[._{color:#BC8F8F;}]]---@language CSS
color.RoyalBlue            = Color(0xFF4169E1) _=[[._{color:#4169E1;}]]---@language CSS
color.SaddleBrown          = Color(0xFF8B4513) _=[[._{color:#8B4513;}]]---@language CSS
color.Salmon               = Color(0xFFFA8072) _=[[._{color:#FA8072;}]]---@language CSS
color.SandyBrown           = Color(0xFFF4A460) _=[[._{color:#F4A460;}]]---@language CSS
color.SeaGreen             = Color(0xFF2E8B57) _=[[._{color:#2E8B57;}]]---@language CSS
color.Seashell             = Color(0xFFFFF5EE) _=[[._{color:#FFF5EE;}]]---@language CSS
color.Sienna               = Color(0xFFA0522D) _=[[._{color:#A0522D;}]]---@language CSS
color.Silver               = Color(0xFFC0C0C0) _=[[._{color:#C0C0C0;}]]---@language CSS
color.SkyBlue              = Color(0xFF87CEEB) _=[[._{color:#87CEEB;}]]---@language CSS
color.SlateBlue            = Color(0xFF6A5ACD) _=[[._{color:#6A5ACD;}]]---@language CSS
color.SlateGray            = Color(0xFF708090) _=[[._{color:#708090;}]]---@language CSS
color.Snow                 = Color(0xFFFFFAFA) _=[[._{color:#FFFAFA;}]]---@language CSS
color.SpringGreen          = Color(0xFF00FF7F) _=[[._{color:#00FF7F;}]]---@language CSS
color.SteelBlue            = Color(0xFF4682B4) _=[[._{color:#4682B4;}]]---@language CSS
color.Tan                  = Color(0xFFD2B48C) _=[[._{color:#D2B48C;}]]---@language CSS
color.Teal                 = Color(0xFF008080) _=[[._{color:#008080;}]]---@language CSS
color.Thistle              = Color(0xFFD8BFD8) _=[[._{color:#D8BFD8;}]]---@language CSS
color.Tomato               = Color(0xFFFD6347) _=[[._{color:#FD6347;}]]---@language CSS
color.Turquoise            = Color(0xFF40E0D0) _=[[._{color:#40E0D0;}]]---@language CSS
color.Violet               = Color(0xFFEE82EE) _=[[._{color:#EE82EE;}]]---@language CSS
color.Wheat                = Color(0xFFF5DEB3) _=[[._{color:#F5DEB3;}]]---@language CSS
color.White                = Color(0xFFFFFFFF) _=[[._{color:#FFFFFF;}]]---@language CSS
color.WhiteSmoke           = Color(0xFFF5F5F5) _=[[._{color:#F5F5F5;}]]---@language CSS
color.Yellow               = Color(0xFFFFFF00) _=[[._{color:#FFFF00;}]]---@language CSS
color.YellowGreen          = Color(0xFF9ACD32) _=[[._{color:#9ACD32;}]]---@language CSS
